services:
  octocatalog:
    build: .
    read_only: true
    ports:
      - "${PORT:-8080}:8080"    
    environment:
      - PORT=8080
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - CONFIG_FILE=/catalog.json
    volumes:
      - ./catalog.json:/catalog.json:ro
    restart: unless-stopped
